[package]
name = "serr_derive"
version = "0.2.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
proc-macro2 = "1.0.95"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
syn = { version = "2.0.103", features = ["full"] }
